name: release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  VERSION: 0.1.1

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Make
        run: sudo apt-get install make

      - name: Run Makefile
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: example-linux
          path: out/example

  # build-windows:
  #   runs-on: windows-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Install Make
  #       run: choco install make

  #     - name: Run Makefile
  #       run: make

  #     - name: Upload artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: example-windows
  #         path: out/example

  release:
    # needs: [build-linux, build-windows]
    needs: [build-linux]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v3

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        draft: false
        prerelease: false
        body: |
          Release ${{ env.VERSION }}
          
          Changes in this Release:
          - This is the first proper release!
        generate_release_notes: true

    - name: Upload Release Asset (Linux)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./example-linux/example
        asset_name: main-linux
        asset_content_type: application/octet-stream

    - name: Upload Release Asset (Windows)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./example-windows/example
        asset_name: main-win
        asset_content_type: application/octet-stream
